# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('N', '未知')], default='未知', max_length=32),
        ),
    ]
